services:
  db:
    image: postgres:16
    container_name: hr_gateway_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: hr_admin
      POSTGRES_PASSWORD: hr_password_DevOnly
      POSTGRES_DB: hr_gateway_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hr_admin -d hr_gateway_db" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  pg_data:
    name: hr_pg_data 
