networks:
  hrnet:

volumes:
  pg_data:

services:
  db:
    image: postgres:16
    container_name: hr_db
    environment:
      POSTGRES_USER: hr_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hr_gateway_db
      TZ: Europe/Bucharest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_admin -d hr_gateway_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [hrnet]
  
  migrator:
    build:
      context: ..
      dockerfile: HR.Gateway.Migrator/Dockerfile
    container_name: hr_migrator
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=hr_gateway_db;Username=hr_admin;Password=${POSTGRES_PASSWORD}"
      ASPNETCORE_ENVIRONMENT: "Production"
      TZ: Europe/Bucharest
    networks: [ hrnet ]
    restart: "no"
  
  gateway:
    build:
      context: ..
      dockerfile: HR.Gateway.Api/Dockerfile
    container_name: hr_gateway
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      TZ: Europe/Bucharest
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=hr_gateway_db;Username=hr_admin;Password=${POSTGRES_PASSWORD}"
      Jwt__Key: "${JWT_SIGNING_KEY}"
      Jwt__Issuer: "HR.Gateway"
      Jwt__Audience: "HR.Gateway.Clients"
      EnableHttpsRedirect: "false"
      EnableSwagger: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    # healthcheck simplu (presupune endpoint /health activ)
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
#      interval: 15s
#      timeout: 5s
#      retries: 10
    restart: unless-stopped
    networks: [hrnet]
